### ISSUE TITLE
Is this compatible with GHCI 8.2?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [snoyberg/conduit#321]
I have a stack.yaml file that looked like this:

```
flags: {}
setup-info:
  ghc:
    linux64:
      8.2.1:
        url: https://downloads.haskell.org/~ghc/8.2.1/ghc-8.2.1-x86_64-deb8-linux.tar.xz
        sha1: 3e52527de6f1cad6d7f1c392ddde8148116d4e36
        content-length: 126809836
extra-deps:
- conduit-1.2.11

- exceptions-0.8.3
- lifted-base-0.2.3.11
- mmorph-1.1.0
- monad-control-1.0.2.2
- mtl-2.2.1
- primitive-0.6.2.0
- resourcet-1.1.9
- transformers-base-0.4.4
- stm-2.4.4.1
- transformers-compat-0.5.1.4

compiler-check: match-exact
compiler: ghc-8.2.1
resolver: ghc-8.2.1
```

All the extra-deps except conduit are things that stack build recommended I add. At this stage it recommends nothing more but it fails to build.
